name: build Hagane COBOL using gcc 9

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-9 build-essential gettext autoconf

      - name: Checkout Hagane COBOL
        uses: actions/checkout@v7
      
      - name: Install Hagane COBOL
        run: |
          ./configure --prefix=/usr/ CC=gcc-9
          make