name: Check Dev Container

on:
  workflow_call:

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: codebuild-opensourcecobol4j-ubuntu-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v7

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.4.0
        with:
          dockerfile: .devcontainer/Dockerfile

  build:
    runs-on: codebuild-opensourcecobol4j-ubuntu-${{ github.run_id }}-${{ github.run_attempt }}
    needs: hadolint
    steps:
      - uses: actions/checkout@v7

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            ./configure
            make
            make install
            cobj --version
          push: never
